### PR TITLE
2017 redesign

### PR DESCRIPTION
**Pull request by jglovier**
Redesigning the site for a fresh take on my work that is more focused on presenting interesting content, but still showcases my work history and projects. 

I've learned a lot of really interesting things over the years working at GitHub, appendTo, and CURE, and I think forcing myself to write about it more intentionally and with a specific audience in mind would help me solidify those lessons internally as well, and give me space for reflection to discover new insights.

So that's my goal for this work.

I'm also going to force myself to do more process writing by posting regular shots of my progress to dribbble along with a thoughtful write up about the work which will help me to think more intentionally about my design choices, keep me in the habbit of writing about design work, and give me a good article as a final product that I can post as a case study on redesigning my own website.

### CODE REVIEW

**Comment by jglovier** [comment]
Been dorking around with some various styles lately. I realized my current iteration is just too busy and graphically distracting. 

As much as I want the site to be really interesting and fun, the design has to be really clear and simple to support the content. 

The content reigns on this site. Everything else is just to help keep your interest long enough to care about the content.

I did some further exploration on the previous style...

image

But ended up really simplifying for the direction I'm currently exploring:

image

...which is funny because it really takes me back to the Tumblr precursor to my 2011 site:

image

**Comment by jglovier** [comment]
Got the sidebar and intro spiked out. 

image

Sidebar TODO:
- [ ] tweak the mid border to possibly extend into the parent padding
  - would need to use an `hr` element instead b/c the current border is just a `border-top` on the `site-nav` element
- [ ] add blue background animation to `site-nav` links
  - make them animate in from the left on hover, and on active
- [ ] wire up the nav to auto-highlight the links when the section is in page view
  - use a class that I can hook to the link background animation
- [ ] add css theme picker
  - use a body class that gets applied with JS to toggle the styles

Intro TODO:
- [ ] make arrow at the bottom
- [ ] create hand waving animation
  - use css animations and transforms (rotate and scale)

**Comment by jglovier** [comment]
Tweaking the design for the intro section a bit...

image

**Comment by jglovier** [comment]
Fleshing out the custom one a bit more...the fingers still need some work on proportions, but the this shows the general concept pretty well:

image

**Comment by jglovier** [comment]
...tidied up a bit:

image

**Comment by chejazi** [comment]
FWIW, when I glanced over the text "content, copy, design and code" my brain instinctively read "copy design and code" which is quite bad :P - might be worth rewording that bit.

**Comment by chejazi** [comment]
I think part of the "dove" effect is the colors. The wave lines are similar in color to water.

**Comment by jglovier** [comment]
>"content, copy, design and code"

@chejazi good catch!

**Comment by jglovier** [comment]
>The wave lines are similar in color to water.

@chejazi Interesting idea...here it is with switched out colors:

image

**Comment by jglovier** [comment]
Great tip re: the colors. I think this makes a lot of sense given the use of the red color over black is very strong, the blue color (as primary color) on the white area is stronger. 🙇 ✨ 🎨

**Comment by jglovier** [comment]
Also the red hand could be perceived as culturally insensitive, so I like using blue for that reason too. :zap:

**Comment by andrewpthorp** [comment]
I really like the new hand, (wasn't a huge fan of the old custom one).

Neat concept!

**Comment by jglovier** [comment]
image

**Comment by andrewpthorp** [comment]
Also, I just realized, the hand in ^ kind of looks like a dove. Not sure if intentional but I like it.

**Comment by jglovier** [comment]
Made some tweaks to the color pallette, and some other layout improvements, include a toggle function to the sidebar nav.

image

image

**Comment by jglovier** [comment]
Did the following today:
- refactored the home page articles and work section to use a `_data` file and single template
- added a collection for case studies and spiked out the case studies template
- ongoing design tweaks
- sidebar is only open on homepage now

**Comment by jglovier** [comment]
Headed a more interesting direction. What I had felt really sterile. Leaning toward a direction with a more published feel.

A sketch:

image

...and a loose comp:

joelglovier-com-mock-2017-10-21

**Comment by jglovier** [comment]
Been working the new direction the past couple months. It's evolved more into a very clean, typography based design with use of hand drawn illustrations.

# Goals

The core user experience I'm aiming for is content consumption, primarily written (case studies and blog posts). At this stage of my career as a product designer, the visual elements of my work - UI design, more specifically - are less important to showcases than the thinking behind my work, which is more strongly conveyed through writing than screenshots.

# Background

The flow I'm optimizing for is someone who arrives at a Google search for my name and generally wants to understand who I am, what I do, and may also be interested in reading some of the things I've written. So for the home page, I'm still using a blend of marketing web design (after all, the site is still intended to serve as a portfolio), and design for a content heavy site needing a gateway home page.

I've used a lot of illustrations and interesting layout on the homepage, and most of the rest of the pages of the site have minimal illustration or other visual elements on the page because they are centered around a reading experience.

# Outstanding questions

- How should the home page sections be arranged? 
  - I think I've made the right decision to put some intro content about myself at first at the top, given my goals. But would it be more impactful to lead with my projects, and keep the about content on a more traditional about page?
  - Given leading with the intro content, should my work history come first, or my projects? I'm not sure which is more impactful, but I'm leaning toward the work history since it contains the case studies that really showcase the design and product thinking work I've done, but also HospitalRun is a really strong proof of my work as well. The projects section only has a couple to showcase for right now though, so until that more robust I'm still leaning toward putting it after the work history.
    - I could actual lead with case studies, and make work history  a separate page. Probably better for a separate pull request though, given I need to get this thing wrapped up after a year of working with no constraints. Time to start imposing some constraints, and iterate on it gradually later now that I've got a much better cadence on working on this thing than I did for the previous 4 years. 😆🙈 
- Are the colleague quotes too long? I'm proud of the things these friends have said about working with me, and I really want to showcase that, but how much will visitors care about reading them? It does speak to an important part about working with me...which is what a few other people actually think about working with me! 😄  
- How do I best structure the content within Jekyll? I've got my writing as articles in Jekyll's default `_posts`, I've got some of my home page content generated from yaml `_data` constructs, and I'm using a separate custom category for the `_case-studies`. Is this the best and most efficient way to structure? I'm pretty sure there's some optimizing that could be done here. 🔧 

# Outstanding tasks

🚨- top priority, I need to finish this before I can merge this PR.
:two: - I'll do it in a separate pull request.
:three:  - I'll get to it later.
:four: - Hopefully I'll get to it eventually. I mean that would be nice, at least.

## 🚢 Roadmap

- [ ] 🚨Finish writing case studies
  - [ ] 2 GitHub case studies
  - [ ] TIME.com RWD appendTo case study
  - [ ] 2 CURE case studies
- [ ] 🚨Responsive styling
- [ ] 🚨Cleanup blog category pages
- [ ] 🚨Cleanup About page
- [ ] 🚨Cleanup Home page
  - [ ] implement fading animations, and possibly some other fun ones like floating illustration elements
  - [ ] incorporate feedback from @emrichard
    - [ ] for what I do images, redraw with the red balls instead of cubes
    - [ ] incorporate the product dev cycle into the infographic so it doesn't feel so separate
    - [ ] try cards with hard edges instead of rounded
    - [ ] make where I work feel less text heavy with better layout (try putting the cards under the info, add a couple UI screenshots, and add more spacing to the sections
    - [ ] fix inconsistent use of N dash in dates
    - [ ] use the juggling pattern elsewhere on the page, maybe put the balls next to main sections too?
    - [ ] try bleeding things off the margin on left/right
- [ ] :two: Refactor CSS
  - [ ] get rid of unused CSS from previous design
  - [ ] refactor mobile styles
  - [ ] look for areas to optimize my use of utility classes
  - [ ] depending on how responsive goes, may need to refactor this as well; it may be faster to do custom styles everywhere I need breakpoints, but ultimately I'd like to use the basscss utility class system for responsive styling
- [ ] :two: Build case studies landing page
- [ ] :two: Blog work
  - [ ] Make additional blog category images
  - [ ] 
- [ ] :three: Rebuild the what I do illustration, and others, with SVG?

# Home

joelglovier-com

# Blog index

joelglovier-com-writing

# Blog page

joelglovier-com-writing-design-advice-for-developers

**Comment by jglovier** [comment]
image

**Pull request merged**
